baseURL = "https://silly-brahmagupta-cf3c26.netlify.app/"
languageCode = "en-us"
title = "Furie.be"
theme = "10ko"
paginate = 10

[author]
  name = "Kevin Danezis"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Un mélange impressionnant de truc (presque) sans intérêt"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Un mélange impressionnant de truc (presque) sans intérêt"
  keywords = "homepage, blog"
  images = [""]

  [favicon]
      [color]
          mask = "#5bbad5"
          msapplication = "#da532c"
          theme = "#ffff"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "10ko Challenge"
    subtitle = ""
    keywords = ""
    #copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Insert cafe here"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"  # And you can even create generic menu
