baseURL = "https://kdanezis.fr"
languageCode = "en-us"
title = "kdanezis.fr"
theme = "10ko"
paginate = 10

[author]
  name = "Kevin Danezis"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Un mélange impressionnant de trucs (presque) sans intérêt qui me passionnent"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Un mélange impressionnant de trucs (presque) sans intérêt qui me passionnent"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/besstiolle/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/besstiolle/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/kevin-danezis/"


  [favicon]
      [color]
          mask = "#5bbad5"
          msapplication = "#da532c"
          theme = "#ffff"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Welcome to the jungle ᕦ(ò_óˇ)ᕤ"
    subtitle = ""
    keywords = ""
    #copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Lire d'autres articles"

    [languages.en.params.logo]
      logoText = "Insert cafe here"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu] 
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = 2
  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "/cv"
    weight     = 1
  [[menu.main]]
    identifier = "about"
    name       = "A propos"
    url        = "/about"
    weight     = 0

[markup.goldmark.renderer]
  unsafe= true