[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.122.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.122.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.122.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.122.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
    from = "/npmjs/*"
    to = "/npmjs/"
    status = 200
    force = true # COMMENT: ensure that we always redirect

#Source : https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

# START custom routing for Plausible Scripting
[[redirects]]
    from = "/js/script.js"
    to = "https://eu.umami.is/script.js"
    status = 200
    force = true # COMMENT: ensure that we always redirect

# [[redirects]]
#     from = "/api/event"
#     to = "https://plausible.io/api/event"
#     status = 200
#     force = true # Ensure that we always redirect
## END custom routing for Plausible Scripting